import { AgentChat } from "@/components/AgentChat";
import { StatusBadge } from "@/components/StatusBadge";
import { User, Crown, CreditCard, Ship, MessageSquare, Star } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { api, type GuestProfile, type IncidentRecord, type ActionProposal } from "@/lib/api";
import { parseTimestamp } from "@/lib/utils";
import { useEffect, useState } from "react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";

function getGuestDisplayName(guest: GuestProfile | undefined) {
  return guest?.fullName ?? guest?.name ?? "Unknown guest";
}

function findGuestById(
  guests: GuestProfile[],
  guestId: string | undefined,
) {
  if (!guestId) return undefined;
  return guests.find(g => g.guestId === guestId || g.id === guestId);
}

function findGuestFromCommandText(guests: GuestProfile[], normalizedText: string) {
  if (!normalizedText) return undefined;

  return guests.find((candidate) => {
    const fullName = String(candidate.fullName ?? '').toLowerCase();
    const shortName = String(candidate.name ?? '').toLowerCase();
    const guestId = String(candidate.guestId ?? '').toLowerCase();
    const docId = String(candidate.id ?? '').toLowerCase();

    const nameMatch = (fullName && normalizedText.includes(fullName)) || (shortName && normalizedText.includes(shortName));
    const idMatch = (guestId && normalizedText.includes(guestId)) || (docId && normalizedText.includes(docId));

    return nameMatch || idMatch;
  });
}

function getGuestIdentifier(guest: GuestProfile | undefined) {
  return guest?.guestId ?? guest?.id;
}

function getIncidentIdentifier(incident: IncidentRecord | undefined) {
  return incident?.incidentId ?? incident?.id ?? "Unknown incident";
}

function formatCurrency(value: number | undefined) {
  if (typeof value !== "number" || Number.isNaN(value)) {
    return "Unknown";
  }

  return value.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 2,
  });
}

function getLoyaltyValueMultiplier(loyaltyTier: string | undefined) {
  switch (String(loyaltyTier).toUpperCase()) {
    case "DIAMOND":
      return 2.0;
    case "ELITE PLATINUM":
      return 1.5;
    case "EMERALD":
      return 1.3;
    case "PLATINUM":
      return 1.1;
    case "GOLD":
    default:
      return 1.0;
  }
}

function getSeverityRisk(severity: string | undefined) {
  switch (String(severity).toLowerCase()) {
    case "critical":
      return 18;
    case "high":
      return 12;
    case "medium":
      return 7;
    default:
      return 3;
  }
}

function getSeverityPriority(severity: string | undefined) {
  const order: Record<string, number> = {
    critical: 6,
    high: 5,
    mediumhigh: 4,
    medium: 3,
    mediumlow: 2,
    low: 1,
  };

  const normalized = String(severity || "")
    .toLowerCase()
    .replace(/[^a-z]/g, "");

  return order[normalized] ?? 0;
}

// ┌─────────────────────────────────────────────────────────────────────────────┐
// │ COUCHBASE INTEGRATION: Guest Recovery Agent Data                           │
// │                                                                             │
// │ Replace static data with live Couchbase queries:                           │
// │                                                                             │
// │ OPTION A — Couchbase Capella:                                              │
// │   • Guest profile: GET from voyageops.guests.guests via Capella SDK      │
// │   • Incidents: SQL++ query on voyageops.guests.incidents               │
// │   • Recommendations: Generated by Capella AI Services (RAG pipeline)       │
// │     using vector search on guest history embeddings                         │
// │     Docs: https://docs.couchbase.com/cloud/vector-search/vector-search.html │
// │   • Timeline: Query voyageops.operations.timeline_events                   │
// │                                                                             │
// │ OPTION B — Couchbase Server:                                               │
// │   • Same SDK calls (portable code)                                         │
// │   • Recommendations: FTS vector search + external LLM                      │
// │     Docs: https://docs.couchbase.com/server/current/fts/fts-introduction.html │
// │   • Eventing Service auto-triggers agent analysis on new incidents         │
// │     Docs: https://docs.couchbase.com/server/current/eventing/eventing-overview.html │
// └─────────────────────────────────────────────────────────────────────────────┘
const GuestRecoveryAgent = () => {
  const POTENTIAL_SCALE = 0.25;
  const EMPTY_GUEST: GuestProfile = {
    guestId: "",
    fullName: "Unknown guest",
    loyaltyTier: "GOLD",
    loyaltyNumber: "Unknown",
    cabinNumber: "Unknown",
    bookingId: "Unknown",
    onboardSpend: 0,
  };

  const [selectedGuestId, setSelectedGuestId] = useState("");
  
  const guestsQuery = useQuery({ queryKey: ["guests"], queryFn: api.guests });
  const guests = guestsQuery.data ?? [];
  
  const incidentsQuery = useQuery({ queryKey: ["incidents", selectedGuestId], queryFn: () => api.incidents({ guestId: selectedGuestId }), enabled: Boolean(selectedGuestId) });
  const proposalsQuery = useQuery({ queryKey: ["proposals", selectedGuestId], queryFn: () => api.actionProposals(selectedGuestId), enabled: Boolean(selectedGuestId), refetchInterval: 10000 });
  const allIncidentsQuery = useQuery({ queryKey: ["incidents", "all"], queryFn: () => api.incidents() });
  const venuesQuery = useQuery({ queryKey: ["venues"], queryFn: api.venues });

  const incidents = incidentsQuery.data ?? [];
  const allIncidents = allIncidentsQuery.data ?? incidentsQuery.data ?? [];
  const venues = venuesQuery.data ?? [];
  const nonClosedIncidents = incidents.filter(inc => String(inc.status).toLowerCase() !== "closed");
  const closedIncidents = incidents.filter(inc => inc.status === "closed");
  const incident = nonClosedIncidents
    .slice()
    .sort((a, b) => {
      const severityDelta = getSeverityPriority(b.severity) - getSeverityPriority(a.severity);
      if (severityDelta !== 0) return severityDelta;

      const updatedA = parseTimestamp(a.updatedAt).getTime();
      const updatedB = parseTimestamp(b.updatedAt).getTime();
      return updatedB - updatedA;
    })[0] ?? incidents[0];

  const severityWeight: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1 };
  const statusWeight: Record<string, number> = { open: 1.2, reviewing: 1.1, approved: 1.0, executed: 0.8, closed: 0.2 };

  const rankedIncidents = allIncidents
    .map(inc => {
      const relatedGuest = findGuestById(guests, inc.guestId);
      const spend = Number(relatedGuest?.onboardSpend ?? 0);
      const potential = Math.round(
        spend *
          (severityWeight[inc.severity] ?? 1) *
          (statusWeight[inc.status] ?? 1) *
          getLoyaltyValueMultiplier(relatedGuest?.loyaltyTier) *
          POTENTIAL_SCALE,
      );
      return { incident: inc, guest: relatedGuest, potential };
    })
    .sort((a, b) => b.potential - a.potential);

  const seenRankedGuestIds = new Set<string>();
  const topRankedIncidents = rankedIncidents
    .filter(({ incident: rankedIncident }) => {
      const guestId = rankedIncident.guestId;
      if (!guestId || seenRankedGuestIds.has(guestId)) {
        return false;
      }
      seenRankedGuestIds.add(guestId);
      return true;
    })
    .slice(0, 10);
  const topGuestIds = Array.from(
    new Set(
      topRankedIncidents
        .map(({ incident: rankedIncident }) => rankedIncident.guestId)
        .filter((guestId): guestId is string => Boolean(guestId)),
    ),
  );
  const topGuestOptions = topGuestIds.map(guestId => ({
    guestId,
    guest: findGuestById(guests, guestId),
  }));

  useEffect(() => {
    if (!selectedGuestId && topGuestIds.length > 0) {
      setSelectedGuestId(topGuestIds[0]);
    }
  }, [selectedGuestId, topGuestIds]);

  const guest = findGuestById(guests, selectedGuestId) ?? topGuestOptions[0]?.guest ?? guests[0] ?? EMPTY_GUEST;
  const selectedProposal = (proposalsQuery.data ?? [])[0];
  const scenarioVenue = incident?.description
    ? venues.find(venue => incident.description.toLowerCase().includes(String(venue.name).toLowerCase()))
    : undefined;
  const occupancyPct = scenarioVenue && scenarioVenue.capacity > 0
    ? Math.round((scenarioVenue.currentOccupancy / scenarioVenue.capacity) * 100)
    : undefined;
  const staffingGapPct = scenarioVenue && scenarioVenue.optimalStaff > 0
    ? Math.max(0, Math.round(((scenarioVenue.optimalStaff - scenarioVenue.staffCount) / scenarioVenue.optimalStaff) * 100))
    : undefined;
  const actionValue = selectedProposal?.actions.reduce((sum, action) => sum + (action.estimatedValue ?? 0), 0) ?? 0;
  const spendValue = Number(guest?.onboardSpend ?? 0);
  const protectedValue = Math.round((spendValue + actionValue) * getLoyaltyValueMultiplier(guest?.loyaltyTier));
  const venueRisk = scenarioVenue?.status === "overloaded" ? 8 : scenarioVenue?.status === "busy" ? 4 : 0;
  const beforeRisk = Math.min(48, getSeverityRisk(incident?.severity) + venueRisk + (String(guest?.loyaltyTier).toUpperCase() === "PLATINUM" ? 10 : 0) + (String(guest?.loyaltyTier).toUpperCase() === "DIAMOND" ? 12 : 0));
  const actionCount = selectedProposal?.actions.length ?? 0;
  const afterRisk = Math.max(4, beforeRisk - Math.min(12, actionCount * 2));
  const actionLabels = selectedProposal?.actions.map(action => action.label).join(", ") ?? "No proposed actions available.";

  const handleChatCommand = (command: string) => {
    const normalized = command.toLowerCase().replace(/[^a-z0-9\s]/g, " ").replace(/\s+/g, " ").trim();
    let nextSelectedGuestId = selectedGuestId;

    const guestFromCommand = findGuestFromCommandText(guests, normalized);
    const commandGuestId = getGuestIdentifier(guestFromCommand);
    if (commandGuestId) {
      nextSelectedGuestId = commandGuestId;
    }
    if (nextSelectedGuestId && nextSelectedGuestId !== selectedGuestId) {
      setSelectedGuestId(nextSelectedGuestId);
    }
  };

  return (
    <div className="p-6 space-y-6 max-w-[1400px] mx-auto">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Guest Service Recovery Agent</h1>
        <p className="text-sm text-muted-foreground mt-0.5">Detect service failures, correlate guest data, and recommend recovery actions</p>
      </div>

      {/* NLP Chat Interface */}
      <AgentChat agentType="guest-recovery" className="h-[520px]" onCommand={handleChatCommand} />

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Left Column - Guest Profile & Incident */}
        <div className="space-y-4">
          {/* Top 10 Guest Selector */}
          {topGuestOptions.length > 0 && (
            <div className="rounded-lg border border-border bg-card p-4">
              <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block mb-2">Select Top-10 Ranked Guest</label>
              <Select value={selectedGuestId} onValueChange={setSelectedGuestId}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select a guest" />
                </SelectTrigger>
                <SelectContent>
                  {topGuestOptions.map(({ guestId, guest: optionGuest }, idx) => {
                    const displayName = optionGuest ? getGuestDisplayName(optionGuest) : `Guest ${guestId}`;

                    return (
                    <SelectItem key={String(guestId)} value={String(guestId)}>
                      #{idx + 1} {displayName}
                    </SelectItem>
                    );
                  })}
                </SelectContent>
              </Select>
            </div>
          )}
          
          {/* Guest Profile */}
          <div className="rounded-lg border border-border bg-card p-4">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">Guest Profile</h2>
            <div className="flex items-start gap-3">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                <User className="h-6 w-6 text-primary" />
              </div>
              <div className="flex-1">
                <p className="font-semibold text-foreground">{getGuestDisplayName(guest)}</p>
                <div className="flex items-center gap-1.5 mt-1">
                  <Crown className="h-3 w-3 text-warning" />
                  <span className="text-xs font-medium text-warning">{guest.loyaltyTier}</span>
                  <span className="text-xs text-muted-foreground">· {guest.loyaltyNumber}</span>
                </div>
              </div>
            </div>
            <div className="mt-4 grid grid-cols-2 gap-3 text-xs">
              <div className="rounded bg-muted p-2">
                <span className="text-muted-foreground">Cabin</span>
                <p className="font-medium text-foreground">{guest.cabinNumber}</p>
              </div>
              <div className="rounded bg-muted p-2">
                <span className="text-muted-foreground">Booking</span>
                <p className="font-medium text-foreground">{guest.bookingId}</p>
              </div>
              <div className="rounded bg-muted p-2">
                <span className="text-muted-foreground flex items-center gap-1"><CreditCard className="h-3 w-3" />Onboard Spend</span>
                <p className="font-medium text-foreground">${guest.onboardSpend.toLocaleString()}</p>
              </div>
              <div className="rounded bg-muted p-2">
                <span className="text-muted-foreground flex items-center gap-1"><Ship className="h-3 w-3" />Sailing History</span>
                <p className="font-medium text-foreground">{guest.sailingHistory ?? guest.sailingHistoryAvg ?? "Unknown"} voyages</p>
              </div>
            </div>
            <div className="mt-3 rounded bg-muted p-2 text-xs">
              <span className="text-muted-foreground flex items-center gap-1"><Star className="h-3 w-3" />Guest Notes</span>
              <p className="text-foreground mt-0.5">{guest.notes ?? "No notes on file."}</p>
            </div>
          </div>

          {/* Active Incident */}
          <div className="rounded-lg border border-destructive/30 bg-card p-4">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3 flex items-center gap-2">
              <MessageSquare className="h-3.5 w-3.5 text-destructive" /> Active Incident
            </h2>
            {incident ? (
              <>
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs font-mono text-muted-foreground">{getIncidentIdentifier(incident)}</span>
                  <StatusBadge status={incident.severity} />
                  <StatusBadge status={incident.status} />
                </div>
                <p className="text-sm font-medium text-foreground">{incident.type}: {incident.category}</p>
                <p className="mt-1.5 text-xs text-muted-foreground leading-relaxed">{incident.description}</p>
                <div className="mt-3 flex gap-4 text-xs text-muted-foreground">
                  <span>Reported: {parseTimestamp(incident.createdAt).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</span>
                  <span>Updated: {parseTimestamp(incident.updatedAt).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</span>
                </div>
              </>
            ) : (
              <p className="text-sm text-muted-foreground">No incidents found for this guest.</p>
            )}
          </div>

          {/* All Active Incidents */}
          <div className="rounded-lg border border-border bg-card p-4">
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">All Guest Incidents</h2>
              <div className="flex gap-4 text-xs">
                <div className="text-right">
                  <span className="text-muted-foreground block">Open</span>
                  <span className="font-semibold text-foreground">{nonClosedIncidents.length}</span>
                </div>
                <div className="text-right">
                  <span className="text-muted-foreground block">Closed</span>
                  <span className="font-semibold text-foreground">{closedIncidents.length}</span>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              {incidents.slice().sort((a, b) => {
                const aIsOpen = String(a.status).toLowerCase() !== "closed" ? 1 : 0;
                const bIsOpen = String(b.status).toLowerCase() !== "closed" ? 1 : 0;
                if (bIsOpen !== aIsOpen) return bIsOpen - aIsOpen;
                const severityDelta = getSeverityPriority(b.severity) - getSeverityPriority(a.severity);
                if (severityDelta !== 0) return severityDelta;
                return parseTimestamp(b.updatedAt).getTime() - parseTimestamp(a.updatedAt).getTime();
              }).map(inc => (
                <div key={getIncidentIdentifier(inc)} className="flex items-center justify-between gap-2 rounded bg-muted p-2 text-xs">
                  <div className="min-w-0">
                    <div className="flex items-center gap-1.5">
                      <span className="font-mono text-muted-foreground">{getIncidentIdentifier(inc)}</span>
                      <StatusBadge status={inc.severity} />
                    </div>
                    <p className="text-foreground mt-0.5 truncate">{inc.type}: {inc.category}</p>
                  </div>
                  <StatusBadge status={inc.status} />
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Center Column - Ranked Incidents */}
        <div className="space-y-4">
          <h2 className="text-sm font-semibold text-foreground">Incidents Ranked by Lost Revenue Potential ({topRankedIncidents.length})</h2>
          {topRankedIncidents.map(({ incident: rankedIncident, guest: rankedGuest, potential }, index) => (
            <div key={getIncidentIdentifier(rankedIncident)} className="rounded-lg border border-border bg-card p-4">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">#{index + 1} Risk Priority</p>
                  <p className="text-sm font-semibold text-foreground">{rankedGuest?.fullName ?? rankedGuest?.name ?? "Unknown Guest"}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-muted-foreground">Est. Lost Revenue Potential</p>
                  <p className="text-sm font-semibold text-destructive">${potential.toLocaleString()}</p>
                </div>
              </div>
              <div className="mt-3 flex items-center gap-2 text-xs">
                <span className="font-mono text-muted-foreground">{getIncidentIdentifier(rankedIncident)}</span>
                <StatusBadge status={rankedIncident.severity} />
                <StatusBadge status={rankedIncident.status} />
              </div>
              <p className="mt-2 text-xs text-muted-foreground line-clamp-2">{rankedIncident.type}: {rankedIncident.category} - {rankedIncident.description}</p>
            </div>
          ))}

        </div>

        {/* Right Column - Approval Queue (worker-generated action_proposals) */}
        <div className="space-y-4">
          <h2 className="text-sm font-semibold text-foreground">Recovery Plan Approval Queue</h2>

          {/* Demo Scenario */}
          <div className="rounded-lg border border-primary/30 bg-primary/5 p-4">
            <h3 className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">Demo Scenario</h3>
            <div className="text-xs text-muted-foreground space-y-2 leading-relaxed">
              <p><strong className="text-foreground">Trigger:</strong> {incident ? `${getGuestDisplayName(guest)} was linked to ${incident.type.toLowerCase()} in ${incident.category}. ${incident.description}` : `No active incident is currently associated with ${getGuestDisplayName(guest)}.`}</p>
              <p><strong className="text-foreground">Analysis:</strong> The agent correlated booking {guest?.bookingId ?? "Unknown"}, loyalty tier {guest?.loyaltyTier ?? "Unknown"}, sailing history {typeof guest?.sailingHistory === "number" ? `${guest.sailingHistory} voyages` : "Unknown"}, and onboard spend {formatCurrency(guest?.onboardSpend)}{scenarioVenue ? ` with ${scenarioVenue.name} operating at ${occupancyPct}% capacity${staffingGapPct ? ` and ${staffingGapPct}% understaffing` : ""}${typeof scenarioVenue.waitTime === "number" ? ` plus a ${scenarioVenue.waitTime}-minute wait time` : ""}` : ""}.</p>
              <p><strong className="text-foreground">Recovery Plan:</strong> {selectedProposal ? `${selectedProposal.actions.length}-action plan from worker proposal ${selectedProposal.proposalId}: ${actionLabels}.` : "No worker-generated action proposal is currently available for this guest."}</p>
              <p><strong className="text-foreground">Outcome:</strong> {selectedProposal ? `Estimated ${formatCurrency(protectedValue)} in future value protected. Churn risk reduced from ${beforeRisk}% to ${afterRisk}% based on current guest value, incident severity, and the proposed actions.` : `Outcome cannot be estimated until a worker proposal is available.`}</p>
            </div>
          </div>

          {proposalsQuery.isLoading && (
            <div className="rounded-lg border border-border bg-card p-4">
              <p className="text-xs text-muted-foreground">Loading proposals…</p>
            </div>
          )}

          {!proposalsQuery.isLoading && (proposalsQuery.data ?? []).length === 0 && (
            <div className="rounded-lg border border-border bg-card p-4">
              <p className="text-xs text-muted-foreground leading-relaxed">
                No agent proposals have been generated for this guest yet. The worker creates a proposal automatically once a pending run is processed for this guest's incident.
              </p>
            </div>
          )}

          {(proposalsQuery.data ?? []).map((proposal: ActionProposal) => (
            <div key={proposal.proposalId} className="rounded-lg border border-border bg-card p-4">
              <div className="flex items-start justify-between gap-2 mb-3">
                <div className="min-w-0 flex-1">
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Agent Proposal</p>
                  <p className="mt-1 text-sm font-medium text-foreground leading-snug">{proposal.summary ?? "Recovery plan ready for review"}</p>
                </div>
                <StatusBadge status={proposal.status as any} />
              </div>

              {proposal.reasoning && (
                <p className="text-xs text-muted-foreground leading-relaxed mb-3 border-l-2 border-primary/30 pl-2">{proposal.reasoning}</p>
              )}

              <div className="space-y-2">
                {proposal.actions.map((action, index) => (
                  <div key={action.actionId} className="rounded-lg border border-border bg-muted/30 p-3">
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0 flex-1">
                        <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Action {index + 1}</p>
                        <p className="mt-1 text-sm font-medium text-foreground">{action.label}</p>
                        {action.description && (
                          <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{action.description}</p>
                        )}
                        {action.estimatedValue ? (
                          <p className="mt-2 text-xs font-medium text-foreground">Estimated value: {formatCurrency(action.estimatedValue)}</p>
                        ) : null}
                      </div>
                      <Button type="button" size="sm" className="shrink-0" onClick={() => undefined}>
                        APPROVE
                      </Button>
                    </div>
                  </div>
                ))}
              </div>

              {proposal.interactive?.followUpQuestions && proposal.interactive.followUpQuestions.length > 0 && (
                <div className="mt-3 pt-3 border-t border-border">
                  <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground mb-1.5">Follow-up Questions</p>
                  <ul className="space-y-1">
                    {proposal.interactive.followUpQuestions.map((q, i) => (
                      <li key={i} className="text-xs text-muted-foreground leading-relaxed">• {q}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ))}

        </div>
      </div>
    </div>
  );
};

export default GuestRecoveryAgent;
